### PR TITLE
More character reference and script errors, DOCTYPE errors

### PR DESCRIPTION
**Pull request by inikulin**
\cc @diervo

### CODE REVIEW

**Comment by diervo** [comment]
@inikulin LGTM, we need to merge html/tests first right?
I will send you soon the remaining DOCTYPE errors to see if the names make sense to you.

**Comment by inikulin** [comment]
@diervo 
> LGTM, we need to merge html/tests first right?

Yeah. 

If you wouldn't mind I'll review it a bit later today.

**Review by diervo — APPROVED** [review]

**Comment by inikulin** [comment]
Sorry for the delay, reviewing now. Meanwhile, can you tale a look at https://github.com/HTMLParseErrorWG/html/pull/10 and https://github.com/HTMLParseErrorWG/html5lib-tests/pull/10?

**Comment by diervo** [comment]
@inikulin Yes Im waiting in particular to merge the DOCTYPE parse errors, since I'm pretty sure tests  will have a lot overlapping between the errors you implemented with the first part + the ones I have left over.

**Comment by diervo** [comment]
Once this is merged, I will pull and do the renaming changes on the remaining errors for Doctype

**Comment by inikulin** [comment]
@diervo Done

**Pull request merged**
