### PR TITLE
Adding parse errors for tag name state

### PR DESCRIPTION
**Pull request by diervo**
Tag Name state parse errors:
https://html.spec.whatwg.org/multipage/syntax.html#tag-name-state:
- Added unexpected-eof-character
- Added unexpected-null-character

### CODE REVIEW

**Comment by diervo** [comment]
@inikulin I haven't included the tests failures for this pr (there are 3) because right now we have like ~200 failing, do you want me to fix those as well?

**Comment by inikulin** [comment]
@diervo Are you sure you rebased on top of latest version of `html5lib-tests`? Where should be no failures, except whose that affected by your change (you can see it in CI results)

**Comment by diervo** [comment]
Running the update.sh Im running into a rebase issue in html from upstream. Other than that, I'm using master from HTMLParseErrorWG in all 3 projects. I don't see the linking between parse5 and htmlt5lib-tests. What am I doing wrong?

**Comment by inikulin** [comment]
Master branch of `parse5` from this org looks for tests in `html5lib-tests` dir which is in the same level as `parse5` dir, e.g.: https://github.com/HTMLParseErrorWG/parse5/blob/master/test/fixtures/tokenizer_test.js#L190

Check that your `update.sh` contains this line: https://gist.github.com/inikulin/b8a9eea7fee5e3438925fb5a3981e777#file-update-sh-L28 I recall adding it later, but I'm not sure if it was before I wrote workflow instructions. Try run `update.sh` and carefully examine output for rebase/pull errors.

**Comment by diervo** [comment]
@inikulin All good, got everything working (I had manually run pull in parse5 so it was not in sync) 
That being said, I do see a rebase (from upstream/master) conflict in html, but we could resolve that later.

Will do the requested changes for the eof error as well.

**Comment by diervo** [comment]
@inikulin Last dependency of the three to merge.

**Pull request merged**
